### ISSUE TITLE
Meaning of negative values 

### ISSUE THREAD

**Issue by milani** [baruchbarzel/NatureBiotech-31-720#2]
Do negative values in `S` mean the same as in correlation matrix? I mean, can we state that `Sij < 0` => opposite relation between values?

Next question, the code comment in [here](https://github.com/baruchbarzel/NatureBiotech-31-720/blob/e84d4fcc18dc14fb1b5cee50dcfecb42f4b9cfc1/SupplementarySoftware1/SILENCING.m#L124) states that if negative values are meaningful, S should be `S = abs(S)/max(max(abs(S)));`. But this always has positive values. Is it a typo?

**Comment by baruchbarzel** [comment]
This is not a coding issue, but rather has to do with the science:

   1. Silencing is exact if Gij is a linear response matrix of the form Gij
   = dx_/dx_j [or d(log x_i) / d(log x_j)]. The best example is a perturbation
   matrix. In this case the positive/negative value of Sij is meaningful - it
   means a an activating/repressing interaction.
   2. The thing is, most users will apply silencing on Gij obtained from
   statistical similarity measures (e.g. correlations, mutual information,
   CLR, etc.). In this case it is approximate. Its supposed to enhance the
   link prediction performance, but not produce a perfect Sij, of course.
   3. In situation 2 often sign has no meaning, especially if, as is often
   done, people use a fully positive correlation matrix to begin with (all
   datasets of DREAM5 on which we tested our method are o that form: 0 < Gij <
   1, namely Gij is already processed to give a ranking between 0 and 1), so
   no info on positive/negative correlations. In this case negative Sij terms
   have no meaning and are regarded as indicating a small likelihood of an
   existing link (similar to Sij ---> 0).

Now, Silencing.m aims to give you a ranked Sij, in which the largest terms
are on the top of the list and the smallest one are at the bottom. So if
you are in case 1 (negative Sij *is* meaningful) Sij = -10 is just as
meaningful as Sij = 10. They both indicate a strong likelihood of a link
(albeit one is repressive and the other is activating, but we are just
asking to expose links here). Hence we use abs(Sij). If, however, you are
in (the more common) scenarios 2,3, Sij = -10 indicates a negligible link
likelihood, while Sij = 10 represents high link probability. Hence we
renormalize the terms so that min(Sij) goes to zero and max(Sij) goes to 1.

Remember - its not the value of Sij or Gij that matters, just the relative
ranking of their terms. These two post-processing renormalizations change
the *values* but preserve the *ranking*: the first (abs) preserves the
ranking of the magnitude of the terms (placing highly negative just as high
as highly positive), the second places the negatives at the bottom.


  <http://u.cs.biu.ac.il/~barzelb/>
Baruch Barzel
Complex Networks Dynamics @ Bar-Ilan University
Ramat Gan
Israel
*Homepage <http://u.cs.biu.ac.il/~barzelb/index.html>*

**Comment by milani** [comment]
Thanks for the great explanation.

**Comment by milani** [comment]
In case 1, assume a positive Gij value (Gij > 0) is transformed to a negative value in S (Sij < 0). Does it mean that the direct relation is repressive and it was the effect of indirect relations that caused Gij to be positive?
